"""
server_pack_export.py - bundle a server's content as a shareable "server pack".

The zip is what people usually hand around for a modded server: server-side
mods (client-only ones stripped by Modrinth hash lookup), configs, scripts,
the loader installer / launcher and a README. No world, no player data, no
Crafty specifics, so it runs on any machine with Java and no Crafty.
"""

import json
import os
import re
import time
import zipfile

from app.classes.minecraft.modpack_installer import ModpackInstaller

# Folders copied whole (when present).
INCLUDE_DIRS = (
    "config",
    "defaultconfigs",
    "kubejs",
    "scripts",
    "global_packs",
    "local",
    "packmenu",
    "openloader",
    "shaderpacks_server",  # rare, harmless
)
# Top-level files copied when present.
INCLUDE_FILES = ("user_jvm_args.txt", "run.sh", "run.bat", "icon.png")
# Never ship these even if they sit inside an included folder.
EXCLUDE_NAMES = {".content_cache", "_backup", "__pycache__", ".DS_Store"}
LOADER_JAR_RE = re.compile(
    r"^(neoforge-installer-.*|forge-installer-.*|fabric|server)\.jar$"
)
EXPORT_DIR = os.path.join(".content_cache", "exports")


def _walk(base, rel_dir):
    root = os.path.join(base, rel_dir)
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_NAMES]
        for fn in filenames:
            if fn in EXCLUDE_NAMES:
                continue
            full = os.path.join(dirpath, fn)
            if os.path.islink(full):
                continue
            yield full, os.path.relpath(full, base).replace(os.sep, "/")


def _detect_loader(server_path):
    """(loader, build, mc) from the installed libraries, best effort."""
    net = os.path.join(server_path, "libraries", "net")
    neo = os.path.join(net, "neoforged", "neoforge")
    if os.path.isdir(neo) and os.listdir(neo):
        build = sorted(os.listdir(neo))[-1]
        parts = build.split(".")
        mc = f"1.{parts[0]}" if parts[1] == "0" else f"1.{parts[0]}.{parts[1]}"
        return "neoforge", build, mc
    forge = os.path.join(net, "minecraftforge", "forge")
    if os.path.isdir(forge) and os.listdir(forge):
        build = sorted(os.listdir(forge))[-1]  # "<mc>-<build>"
        return "forge", build, build.split("-")[0]
    if os.path.exists(os.path.join(server_path, "fabric.jar")):
        return "fabric", None, None
    for fn in os.listdir(server_path):
        m = re.match(r"^(neoforge|forge)-installer-([0-9.]+)\.jar$", fn)
        if m:
            return m.group(1), None, m.group(2)
    return None, None, None


def _readme(name, loader, build, mc, installer_jar, removed):
    lines = [
        f"{name} - server pack",
        "=" * (len(name) + 14),
        "",
        f"Minecraft {mc or '?'} / {loader or '?'}" + (f" {build}" if build else ""),
        "Generated by Crafty Controller (modpack browser fork).",
        "",
        "This archive contains the server-side mods and configs only:",
        "no world, no player data, no server.properties. Client-only mods",
        "were removed automatically.",
        "",
        "Requirements: Java 21 (NeoForge/Forge 1.20.5+ and Fabric 1.21+).",
        "",
        "How to run",
        "----------",
        "1. Unzip into an empty folder.",
    ]
    if loader in ("neoforge", "forge"):
        if installer_jar:
            lines.append(
                f"2. Install the loader once:  java -jar {installer_jar} "
                "--installServer"
            )
        else:
            lines.append(
                f"2. Download the {loader} installer for {mc} {build or ''} from the "
                "official site and run:  java -jar <installer>.jar --installServer"
            )
        lines += [
            "3. Accept the EULA: set eula=true in eula.txt",
            "4. Start:  ./run.sh  (Linux/macOS)   or   run.bat  (Windows)",
            "   Memory is set in user_jvm_args.txt (e.g. -Xmx6G).",
        ]
    elif loader == "fabric":
        lines += [
            "2. Accept the EULA: set eula=true in eula.txt",
            "3. Start:  java -Xmx6G -jar fabric.jar nogui",
        ]
    else:
        lines += ["2. Install the matching loader, accept the EULA, start the server."]
    lines += [
        "",
        "The first start creates a fresh world. To open the server to the",
        "internet, forward the port from server.properties (default 25565).",
    ]
    if removed:
        lines += ["", "Client-only mods left out:"] + [f"  - {r}" for r in removed]
    return "\n".join(lines) + "\n"


def export_server_pack(server_path, name, progress_cb=None):
    """Write <server>/.content_cache/exports/<slug>-server-pack.zip.

    Returns (relative zip path, summary dict)."""
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-") or "server"
    loader, build, mc = _detect_loader(server_path)
    installer_jar = next(
        (
            fn
            for fn in sorted(os.listdir(server_path))
            if LOADER_JAR_RE.match(fn) and fn != "server.jar"
        ),
        None,
    )

    # Server-side mods only: hash every active jar and drop client-only ones.
    mods_dir = os.path.join(server_path, "mods")
    jars = {}
    if os.path.isdir(mods_dir):
        for fn in sorted(os.listdir(mods_dir)):
            full = os.path.join(mods_dir, fn)
            if fn.endswith(".jar") and os.path.isfile(full):
                jars[fn] = full
    installer = ModpackInstaller(server_path)
    hashes = {fn: installer.sha1_of(full) for fn, full in jars.items()}
    projects = installer.lookup_sides(list(hashes.values()))
    removed = [
        fn
        for fn, sha in hashes.items()
        if (projects.get(sha) or {}).get("server_side") == "unsupported"
    ]
    keep = [fn for fn in jars if fn not in removed]

    out_dir = os.path.join(server_path, EXPORT_DIR)
    os.makedirs(out_dir, exist_ok=True)
    zip_rel = f"{EXPORT_DIR}/{slug}-server-pack.zip".replace(os.sep, "/")
    zip_path = os.path.join(server_path, zip_rel)
    tmp = zip_path + ".part"
    total = len(keep)
    count = 0
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED, compresslevel=1) as zf:
        for fn in keep:
            zf.write(jars[fn], f"mods/{fn}")
            count += 1
            if progress_cb and count % 10 == 0:
                progress_cb({"current": fn, "done": count, "total": total})
        for rel_dir in INCLUDE_DIRS:
            if os.path.isdir(os.path.join(server_path, rel_dir)):
                for full, rel in _walk(server_path, rel_dir):
                    zf.write(full, rel)
        for fn in INCLUDE_FILES:
            full = os.path.join(server_path, fn)
            if os.path.isfile(full):
                zf.write(full, fn)
        if installer_jar:
            zf.write(os.path.join(server_path, installer_jar), installer_jar)
        zf.writestr("eula.txt", "eula=false\n")
        zf.writestr(
            "server-pack.json",
            json.dumps(
                {
                    "name": name,
                    "minecraft": mc,
                    "loader": loader,
                    "loader_build": build,
                    "mods": keep,
                    "client_only_removed": removed,
                    "generated": time.strftime("%Y-%m-%dT%H:%M:%S"),
                    "generator": "crafty-controller modpack browser",
                },
                indent=2,
            ),
        )
        zf.writestr(
            "README-SERVER.txt",
            _readme(name, loader, build, mc, installer_jar, removed),
        )
    os.replace(tmp, zip_path)
    return zip_rel, {
        "path": zip_rel,
        "size": os.path.getsize(zip_path),
        "mods": len(keep),
        "removed": removed,
        "loader": loader,
        "loader_build": build,
        "mc": mc,
        "installer": installer_jar,
    }
